extern const GeoLayout lll_area_1_geo[];
extern const GeoLayout lll_area_1[];
extern const Collision lll_area_1_collision[];
extern const MacroObject lll_area_1_macro_objs[];
extern u8 lll_dl_Texture0528_RGB_ci8[];
extern u8 lll_dl_Texture0528_RGB_pal_rgba16[];
extern u8 lll_dl_anvil__11__i8[];
extern u8 lll_dl_stonebrick_cracked__7__i8[];
extern u8 lll_dl_angelic_stone_i8[];
extern u8 lll_dl_granite__11__i8[];
extern u8 lll_dl_quartz_block_lines_i8[];
extern u8 lll_dl__09006800_ci8[];
extern u8 lll_dl__09006800_pal_rgba16[];
extern Vtx lll_dl_area_geo_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_area_geo_mesh_layer_1_vtx_0[60];
extern Gfx lll_dl_area_geo_mesh_layer_1_tri_0[];
extern Vtx lll_dl_area_geo_mesh_layer_1_vtx_1[103];
extern Gfx lll_dl_area_geo_mesh_layer_1_tri_1[];
extern Vtx lll_dl_area_geo_mesh_layer_1_vtx_2[296];
extern Gfx lll_dl_area_geo_mesh_layer_1_tri_2[];
extern Vtx lll_dl_area_geo_mesh_layer_1_vtx_3[412];
extern Gfx lll_dl_area_geo_mesh_layer_1_tri_3[];
extern Vtx lll_dl_area_geo_mesh_layer_1_vtx_4[18];
extern Gfx lll_dl_area_geo_mesh_layer_1_tri_4[];
extern Vtx lll_dl_area_geo_mesh_layer_1_vtx_5[80];
extern Gfx lll_dl_area_geo_mesh_layer_1_tri_5[];
extern Vtx lll_dl_area_geo_mesh_layer_6_vtx_cull[8];
extern Vtx lll_dl_area_geo_mesh_layer_6_vtx_0[12];
extern Gfx lll_dl_area_geo_mesh_layer_6_tri_0[];
extern Gfx mat_lll_dl_lava[];
extern Gfx mat_revert_lll_dl_lava[];
extern Gfx mat_lll_dl_floor_layer1[];
extern Gfx mat_revert_lll_dl_floor_layer1[];
extern Gfx mat_lll_dl_wall_layer1[];
extern Gfx mat_revert_lll_dl_wall_layer1[];
extern Gfx mat_lll_dl_stone_layer1[];
extern Gfx mat_revert_lll_dl_stone_layer1[];
extern Gfx mat_lll_dl_f3dlite_material_010_layer1[];
extern Gfx mat_revert_lll_dl_f3dlite_material_010_layer1[];
extern Gfx mat_lll_dl_pillar_layer1[];
extern Gfx mat_revert_lll_dl_pillar_layer1[];
extern Gfx mat_lll_dl_flame_thrower[];
extern Gfx mat_revert_lll_dl_flame_thrower[];
extern Gfx lll_dl_area_geo_mesh_layer_1[];
extern Gfx lll_dl_area_geo_mesh_layer_6[];
